/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedActionLogsRouteImport } from './routes/_protected/action-logs'
import { Route as ProtectedAnalysesRouteImport } from './routes/_protected/analyses'
import { Route as ProtectedChatsRouteImport } from './routes/_protected/chats'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedDiagnosticsRouteImport } from './routes/_protected/diagnostics'
import { Route as ProtectedMailRouteImport } from './routes/_protected/mail'
import { Route as ProtectedMessagesRouteImport } from './routes/_protected/messages'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedTelegramRouteImport } from './routes/_protected/telegram'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedActionLogsRoute = ProtectedActionLogsRouteImport.update({
  id: '/action-logs',
  path: '/action-logs',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAnalysesRoute = ProtectedAnalysesRouteImport.update({
  id: '/analyses',
  path: '/analyses',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedChatsRoute = ProtectedChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDiagnosticsRoute = ProtectedDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMailRoute = ProtectedMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMessagesRoute = ProtectedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTelegramRoute = ProtectedTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/action-logs': typeof ProtectedActionLogsRoute
  '/analyses': typeof ProtectedAnalysesRoute
  '/chats': typeof ProtectedChatsRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/diagnostics': typeof ProtectedDiagnosticsRoute
  '/mail': typeof ProtectedMailRoute
  '/messages': typeof ProtectedMessagesRoute
  '/settings': typeof ProtectedSettingsRoute
  '/telegram': typeof ProtectedTelegramRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/action-logs': typeof ProtectedActionLogsRoute
  '/analyses': typeof ProtectedAnalysesRoute
  '/chats': typeof ProtectedChatsRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/diagnostics': typeof ProtectedDiagnosticsRoute
  '/mail': typeof ProtectedMailRoute
  '/messages': typeof ProtectedMessagesRoute
  '/settings': typeof ProtectedSettingsRoute
  '/telegram': typeof ProtectedTelegramRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/action-logs': typeof ProtectedActionLogsRoute
  '/_protected/analyses': typeof ProtectedAnalysesRoute
  '/_protected/chats': typeof ProtectedChatsRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/diagnostics': typeof ProtectedDiagnosticsRoute
  '/_protected/mail': typeof ProtectedMailRoute
  '/_protected/messages': typeof ProtectedMessagesRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/telegram': typeof ProtectedTelegramRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/action-logs'
    | '/analyses'
    | '/chats'
    | '/dashboard'
    | '/diagnostics'
    | '/mail'
    | '/messages'
    | '/settings'
    | '/telegram'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/action-logs'
    | '/analyses'
    | '/chats'
    | '/dashboard'
    | '/diagnostics'
    | '/mail'
    | '/messages'
    | '/settings'
    | '/telegram'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/_protected/action-logs'
    | '/_protected/analyses'
    | '/_protected/chats'
    | '/_protected/dashboard'
    | '/_protected/diagnostics'
    | '/_protected/mail'
    | '/_protected/messages'
    | '/_protected/settings'
    | '/_protected/telegram'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/action-logs': {
      id: '/_protected/action-logs'
      path: '/action-logs'
      fullPath: '/action-logs'
      preLoaderRoute: typeof ProtectedActionLogsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/analyses': {
      id: '/_protected/analyses'
      path: '/analyses'
      fullPath: '/analyses'
      preLoaderRoute: typeof ProtectedAnalysesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/chats': {
      id: '/_protected/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ProtectedChatsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/diagnostics': {
      id: '/_protected/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof ProtectedDiagnosticsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/mail': {
      id: '/_protected/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof ProtectedMailRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/messages': {
      id: '/_protected/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof ProtectedMessagesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/telegram': {
      id: '/_protected/telegram'
      path: '/telegram'
      fullPath: '/telegram'
      preLoaderRoute: typeof ProtectedTelegramRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedActionLogsRoute: typeof ProtectedActionLogsRoute
  ProtectedAnalysesRoute: typeof ProtectedAnalysesRoute
  ProtectedChatsRoute: typeof ProtectedChatsRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedDiagnosticsRoute: typeof ProtectedDiagnosticsRoute
  ProtectedMailRoute: typeof ProtectedMailRoute
  ProtectedMessagesRoute: typeof ProtectedMessagesRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedTelegramRoute: typeof ProtectedTelegramRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedActionLogsRoute: ProtectedActionLogsRoute,
  ProtectedAnalysesRoute: ProtectedAnalysesRoute,
  ProtectedChatsRoute: ProtectedChatsRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedDiagnosticsRoute: ProtectedDiagnosticsRoute,
  ProtectedMailRoute: ProtectedMailRoute,
  ProtectedMessagesRoute: ProtectedMessagesRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedTelegramRoute: ProtectedTelegramRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
