import { driver, type DriveStep } from 'driver.js'
import 'driver.js/dist/driver.css'

const MOBILE_BREAKPOINT = 820

function isMobile(): boolean {
    return typeof window !== 'undefined' && window.innerWidth <= MOBILE_BREAKPOINT
}

function buildSteps(mobile: boolean): DriveStep[] {
    // On mobile the sidebar is hidden — use the bottom nav instead.
    const navEl = (path: string) =>
        mobile ? `.app-mobile-nav a[href="${path}"]` : `.app-sidebar-nav a[href="${path}"]`
    const navSide = mobile ? ('top' as const) : ('right' as const)

    return [
        // Step 1 — intro landmark: sidebar on desktop, topbar on mobile
        {
            element: mobile ? '.app-topbar' : '.app-sidebar',
            popover: {
                title: mobile ? 'Welcome to Employed' : 'Navigation & Control',
                description: mobile
                    ? 'This top bar shows your current page, live worker status, and quick access to theme and tour controls.'
                    : 'Switch between Overview, Messages inbox, AI Verdicts, Mail composer, Telegram connection, and Automation Settings.',
                side: mobile ? ('bottom' as const) : ('right' as const),
                align: mobile ? ('center' as const) : ('start' as const),
            },
        },

        // Step 2 — worker status pill (same element on both, adjust side)
        {
            element: '.worker-pill',
            popover: {
                title: 'Live Worker Status',
                description:
                    'Shows whether your background Node worker is online and actively monitoring Telegram channels.',
                side: 'bottom' as const,
                align: 'end' as const,
            },
        },

        // Step 3 — nav container (bottom bar on mobile, sidebar title area on desktop)
        {
            element: mobile ? '.app-mobile-nav' : '.topbar-title',
            popover: {
                title: mobile ? 'Navigation Bar' : 'Current Page & Sidebar Toggle',
                description: mobile
                    ? 'Tap icons here to switch between Overview, Messages, Analyses, Mail, Chats, and all other sections.'
                    : 'View current section details or click the toggle button to collapse/expand the sidebar anytime.',
                side: mobile ? ('top' as const) : ('bottom' as const),
                align: mobile ? ('center' as const) : ('start' as const),
            },
        },

        // Steps 4–7 — individual nav links (selector & side adapt automatically)
        {
            element: navEl('/messages'),
            popover: {
                title: 'Messages Inbox',
                description:
                    'Every incoming message from your monitored Telegram channels is recorded and stored here in real time.',
                side: navSide,
                align: 'center' as const,
            },
        },
        {
            element: navEl('/analyses'),
            popover: {
                title: 'AI Analyses & Verdicts',
                description:
                    'View structured JSON extractions (jobs, freelance gigs, leads, or urgent alerts) generated by LLMs on incoming messages.',
                side: navSide,
                align: 'center' as const,
            },
        },
        {
            element: navEl('/mail'),
            popover: {
                title: 'Mail Composer',
                description:
                    'Auto-detect recruiter emails from job posts, attach your CV/Resume PDF, and send customised job applications.',
                side: navSide,
                align: 'center' as const,
            },
        },
        {
            element: navEl('/settings'),
            popover: {
                title: 'Automation & Rules',
                description:
                    'Configure LLM prompt templates, set up Email/Telegram/Webhook notifiers, and create automated trigger rules.',
                side: navSide,
                align: 'center' as const,
            },
        },
    ]
}

export function startTour() {
    const mobile = isMobile()

    const driverObj = driver({
        showProgress: true,
        animate: true,
        allowClose: true,
        doneBtnText: 'Finish Tour',
        nextBtnText: 'Next',
        prevBtnText: 'Back',
        popoverClass: 'employed-driver-popover',
        steps: buildSteps(mobile),
        onDestroyed: () => {
            if (typeof window !== 'undefined') {
                localStorage.setItem('employed_tour_completed', 'true')
            }
        },
    })

    driverObj.drive()
}

export function isTourCompleted(): boolean {
    if (typeof window !== 'undefined') {
        return localStorage.getItem('employed_tour_completed') === 'true'
    }
    return true
}
