import { driver } from 'driver.js'
import 'driver.js/dist/driver.css'

export function startTour() {
    const driverObj = driver({
        showProgress: true,
        animate: true,
        allowClose: true,
        doneBtnText: 'Finish Tour',
        nextBtnText: 'Next',
        prevBtnText: 'Back',
        popoverClass: 'employed-driver-popover',
        steps: [
            {
                element: '.app-sidebar',
                popover: {
                    title: 'Navigation & Control',
                    description:
                        'Switch between Overview, Messages inbox, AI Verdicts, Mail composer, Telegram connection, and Automation Settings.',
                    side: 'right',
                    align: 'start',
                },
            },
            {
                element: '.worker-pill',
                popover: {
                    title: 'Live Worker Status',
                    description:
                        'Shows whether your background Node worker is online and actively monitoring Telegram channels.',
                    side: 'bottom',
                    align: 'end',
                },
            },
            {
                element: '.topbar-title',
                popover: {
                    title: 'Current Page & Sidebar Toggle',
                    description:
                        'View current section details or click the toggle button to collapse/expand the sidebar anytime.',
                    side: 'bottom',
                    align: 'start',
                },
            },
            {
                element: '.app-sidebar-nav a[href="/messages"]',
                popover: {
                    title: 'Messages Inbox',
                    description:
                        'Every incoming message from your monitored Telegram channels is recorded and stored here in real time.',
                    side: 'right',
                    align: 'center',
                },
            },
            {
                element: '.app-sidebar-nav a[href="/analyses"]',
                popover: {
                    title: 'AI Analyses & Verdicts',
                    description:
                        'View structured JSON extractions (jobs, freelance gigs, leads, or urgent alerts) generated by LLMs on incoming messages.',
                    side: 'right',
                    align: 'center',
                },
            },
            {
                element: '.app-sidebar-nav a[href="/mail"]',
                popover: {
                    title: 'Mail Composer',
                    description:
                        'Auto-detect recruiter emails from job posts, attach your CV/Resume PDF, and send customized job applications.',
                    side: 'right',
                    align: 'center',
                },
            },
            {
                element: '.app-sidebar-nav a[href="/settings"]',
                popover: {
                    title: 'Automation & Rules',
                    description:
                        'Configure LLM prompt templates, set up Email/Telegram/Webhook notifiers, and create automated trigger rules.',
                    side: 'right',
                    align: 'center',
                },
            },
        ],
        onDestroyed: () => {
            if (typeof window !== 'undefined') {
                localStorage.setItem('employed_tour_completed', 'true')
            }
        },
    })

    driverObj.drive()
}

export function isTourCompleted(): boolean {
    if (typeof window !== 'undefined') {
        return localStorage.getItem('employed_tour_completed') === 'true'
    }
    return true
}
